EWebApp/Controllers/ClothingController.cs
using EWebApp.Data;
using EWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EWebApp.Controllers
{
    public class ClothingController : Controller
    {
        private readonly IProductRepository _products;

        public ClothingController(IProductRepository products)
        {

            _products = products;
        }
        public async Task<IActionResult> Index()
        {

            var allKitchen = await _products.GetByCategoriesAsync(ProductCategory.Clothing);

            return View(allKitchen);
        }
    }
}

EWebApp/Controllers/FurnitureController.cs
using EWebApp.Data;
using EWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EWebApp.Controllers
{
    public class FurnitureController : Controller
    {
        private readonly IProductRepository _products;

        public FurnitureController(IProductRepository products)
        {

            _products = products;
        }
        public async Task<IActionResult> Index()
        {

            var allKitchen = await _products.GetByCategoriesAsync(ProductCategory.Furniture);

            return View(allKitchen);
        }


        
    }
}

EWebApp/Controllers/KitchenController.cs
using EWebApp.Data;
using EWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EWebApp.Controllers
{
    public class KitchenController : Controller
    {
        private readonly IProductRepository _products;

        public KitchenController(IProductRepository products)
        {
            
            _products = products;
        }
        public async Task<IActionResult> Index()
        {

            var allKitchen = await _products.GetByCategoriesAsync(ProductCategory.Kitchen);

            return View(allKitchen);
        }
    }
}

EWebApp/Controllers/OrderController.cs
using EWebApp.Data.Services;
using EWebApp.Models;
using EWebApp.Models.Shopping;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EWebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrderController(IProductRepository productRepository,
                               ShoppingCart shoppingCart,
                               IOrdersService ordersService)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index ()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.shoppingCartItems = items;

            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productRepository.GetByIdAync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction("ShoppingCart");
        }

        public async Task<IActionResult> RemoveItemToShoppingCart(int id)
        {
            var item = await _productRepository.GetByIdAync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction("ShoppingCart");
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}
    

EWebApp/Controllers/ProductionController.cs
using EWebApp.Dbclass;
using EWebApp.Models;
using EWebApp.Models.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EWebApp.Controllers
{
    public class ProductionController : Controller
    {
        private readonly IProductRepository _products;
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductionController(IProductRepository products, AppDbContext context,
                                    IWebHostEnvironment hostEnvironment)
        {
            _products = products;
            _context = context;
            _hostEnvironment = hostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var allproduct = await _products.GetAllAsync();
            return View(allproduct);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            

            var allproduct = await _products.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allproduct.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();
                if (filteredResult == null)
                {
                    return View("Filter", filteredResult);

                }
                else
                    return View("Filter");
                
            }
            return View("Index", allproduct);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
          /*  var productService = new ProductRepository(_context);
            var productTypes = await productService.GetAllCategoriesAsync();

            var productTypeSelectedList = productTypes.Select(pt => new SelectListItem
            {
                Value = ((int)pt).ToString(),
                Text = pt.ToString(),
            }).ToList();

            ViewBag.ProductTypeSelectList = productTypeSelectedList;*/


            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Products newProduct = new Products()
                {
                    Name = model.Name,
                    Price = model.Price,
                    ProduceCategory = model.ProduceCategory,
                    Description = model.Description,
                    Photo = uniqueFileName
                };
                _context.Products.AddAsync(newProduct);
                _context.SaveChanges();

                return RedirectToAction("details", new { id = newProduct.Id });
            }
            return View();
        }




        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            
            var getProducts = await _products.GetByIdAync(id.Value);

            if (getProducts == null)
            {
                Response.StatusCode = 404;
                return View("NotFound", id.Value);
            }

            ProductDetailsViewModel viewModel = new ProductDetailsViewModel()
            {
                products = getProducts
                
            };

            return View(viewModel);


        }

        private string ProcessUploadedFile(ProductCreateViewModel model)
        {
            string uniqueFileName = " ";
            if (model.ProductPhoto != null)
            {
                string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "Images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProductPhoto.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProductPhoto.CopyTo(fileStream);

                }
            }

            return uniqueFileName;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _products.GetByIdAync(id);
            if (productDetails == null) return View("NotFound");

            
            
                var response = new EditProductViewModel()
                {
                    Id = productDetails.Id,
                    Name = productDetails.Name,
                    Price = productDetails.Price,
                    Description = productDetails.Description,
                    ProduceCategory = productDetails.ProduceCategory,
                    EditPhoto = productDetails.Photo

                };
                return View(response);
            
        }

        [HttpPost]
        public async Task<IActionResult> Edit (EditProductViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                var product = await _products.GetByIdAync(model.Id);

                
                    product.Name = model.Name;
                    product.Price = model.Price;
                    product.Description = model.Description;
                    product.ProduceCategory = model.ProduceCategory;
                    if(model.ProductPhoto != null)
                    {
                        if(model.EditPhoto != null)
                        {
                            string filePath = Path.Combine(_hostEnvironment.WebRootPath, "Images", model.EditPhoto);
                            System.IO.File.Delete(filePath);

                        }
                         product.Photo = ProcessUploadedFile(model);

                    }

                await _products.UpdateAsync(product); 
                
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete (int id)
        {
            var product = await _products.GetByIdAync(id);
            if (product != null)
            {
                await _products.DeleteAsync(product.Id);
                return RedirectToAction("Index", "Production");
            }

            return View("NotFound");


        }




    }


}
      

EWebApp/Views/Production/Create.cshtml
@model ProductCreateViewModel
@using EWebApp.Data;

@{
    ViewData["Title"] = "Create New Product";

}








<form enctype="multipart/form-data" asp-action="Create" method="post" class="mt-3">
    <h1>Add a New Product</h1>
    <div asp-validation-summary="All" class="text-danger"></div>


    <div class="form-group row mt-3">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" placeholder="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mt-3">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" placeholder="Description"/>
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>
    </div>


    <div class="form-group row mt-3">
        <label asp-for="Price" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Price" type="number" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>

        </div>
    </div>
    <div class="form-group row mt-3">

        <label asp-for="ProduceCategory" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">
            <select asp-for="ProduceCategory" asp-items="Html.GetEnumSelectList<ProductCategory>()" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                <option value="">Please Select</option>
            </select>
            

            <span asp-validation-for="ProduceCategory" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="ProductPhoto" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input multiple asp-for="ProductPhoto" class="form-control custom-file-input" />
                

            </div>

        </div>
    </div>



    <div class="form-group row mt-3">
        <div class="col-sm-10">

            <Button asp-action="create" asp-controller="Production" type="submit" value="Create" class="btn btn-outline-success"> Create </Button>
            <a asp-controller="Production" class="btn btn-outline-secondary" asp-action="Index">Show All</a>
        </div>
    </div>

    

</form>

EWebApp/Views/Production/Details.cshtml
@model ProductDetailsViewModel

@{
    ViewData["Title"] = "Details";
    var photoPath = "~/Images/";
    if (string.IsNullOrEmpty(Model.products.Photo))
    {
        photoPath += "me.jpg";
    }
    else
    {
        photoPath += Model.products.Photo;
    }
}

<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.products.Name</h1>
            </div>
            <div class="card-body" text-center>
                <img class="card-img-top" src="@photoPath" asp-append-version="true" />

                <h4>Product Category : @Model.products.ProduceCategory</h4>
                <h4>Price : @Model.products.Price</h4>
                <h4>Description : @Model.products.Description</h4>


            </div>
            <div class="card-footer" text-center>
                <a asp-controller="Production" asp-action="index" class="btn btn-primary"><i class="bi bi-back">Back</i></a>
                <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@Model.products.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart (Price: @Model.products.Price.ToString("c"))</i></a>
                
            </div>
        </div>
    </div>
</div>

EWebApp/Views/Production/Edit.cshtml
@model EditProductViewModel

@{
    ViewData["Title"] = "Edit Product";

    var photoPath = "~/Images/";
    if (string.IsNullOrEmpty(Model.EditPhoto))
    {
        photoPath += "me.jpg";
    }
    else
    {
        photoPath += Model.EditPhoto;
    }
}



<form enctype="multipart/form-data" asp-action="Edit" method="post" class="mt-3">
    <input hidden asp-for="Id" />
    <input hidden asp-for="EditPhoto" />
    <h1>Edit Product</h1>
    <span asp-validation-summary="All" class="text-danger"></span>

    <div class="form-group row mt-3">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" placeholder="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mt-3">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>
    </div>


    <div class="form-group row mt-3">
        <label asp-for="Price" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Price" type="number" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>

        </div>
    </div>
    <div class="form-group row mt-3">

        <label asp-for="ProduceCategory" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">
            <select asp-for="ProduceCategory" asp-items="Html.GetEnumSelectList<ProductCategory>()" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                <option value="">Please Select</option>
            </select>


            <span asp-validation-for="ProduceCategory" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="ProductPhoto" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input multiple asp-for="ProductPhoto" class="form-control custom-file-input" />


            </div>

        </div>
    </div>



    <div class="form-group row mt-3">
        <div class="col-sm-10">

            <Button asp-action="Edit" asp-controller="Production" asp-route-id="@Model.Id" type="submit" value="Create" class="btn btn-outline-success">Update</Button>
            <a asp-controller="Production" class="btn btn-outline-secondary" asp-action="Index">Show All</a>
        </div>
    </div>

    <div class="form-group row col-sm-4 offset-4">
        <img src="@photoPath" class="imageThumbnail" asp-append-version="true" />

    </div>

</form>
@section Scripts {

    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
}

EWebApp/Views/Production/Filter.cshtml
@model IEnumerable<Products>



@{
    ViewData["Title"] = "Filter";
}

<div class="container">

    <div class="card-header text-center">
        <h3>Filter</h3>
    </div>

    @if(Model == null)
    {
        <div class="alert alert-danger mt-2 mb-1">
            
            <hr />
            <h5>
                The searched Product cannot be found.
            </h5>
        </div>
        <a asp-action="index" asp-controller="Production" class="btn btn-outline-success">
            Click here to see the list of all Products
        </a>
    }
    else
    {

        @foreach (var items in Model)
        {
            var photoPath = "~/Images/";
            if (string.IsNullOrEmpty(items.Photo))
            {
                photoPath += "me.jpg";
            }
            else
            {
                photoPath += items.Photo;
            }

            <div class="col-md-4 col-xs-6 border-primary d-inline-flex ">
                <div class="crow card flex-grow-0" style="max-width: 540px">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title text-center">
                                        @items.Name
                                    </h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <img src="@photoPath" asp-append-version="true" class="imageThumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@items.Description</p>
                                <p class="card-text">@items.Price.ToString("c")</p>

                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text">
                                    <a asp-action="Details" asp-controller="Production" asp-route-id="@items.Id" class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill">Show Details</i></a>
                                    <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@items.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart(Price: @items.Price.ToString("c"))</i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }


    }
   
    

</div>

EWebApp/Views/Production/Index.cshtml
@model IEnumerable<Products>

@{
    ViewData["Title"] = "All Products";

}

<div class="container">

    <div class="card-header text-center">
        <h3>Furnitures</h3>
    </div>
    @foreach (var items in Model)
    {
        var photoPath = "~/Images/";
        if (string.IsNullOrEmpty(items.Photo))
        {
            photoPath += "me.jpg";
        }
        else
        {
            photoPath += items.Photo;
        }
        if (items.ProduceCategory == ProductCategory.Furniture)

        {


            <div class="col-md-4 col-xs-6 border-primary d-inline-flex ">
                <div class="crow card flex-grow-0" style="max-width: 540px">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title text-center">
                                        @items.Name
                                    </h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <img src="@photoPath" asp-append-version="true" class="imageThumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@items.Description</p>
                                <p class="card-text">@items.Price.ToString("c")</p>

                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text">
                                    <a asp-action="Details" asp-controller="Production" asp-route-id="@items.Id" class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill">Show Details</i></a>
                                    <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@items.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart(Price: @items.Price.ToString("c"))</i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    <div class="card-footer mb-3 text-center"> <a asp-action="index" asp-controller="Furniture" class="btn float-right">More....</a></div>
</div>

<div class="container">

    <div class="card-header text-center">
        <h3>Appliances</h3>
    </div>
    @foreach (var items in Model)
    {
        var photoPath = "~/Images/";
        if (string.IsNullOrEmpty(items.Photo))
        {
            photoPath += "me.jpg";
        }
        else
        {
            photoPath += items.Photo;
        }
        if (items.ProduceCategory == ProductCategory.Appliances)
        {

            <div class="col-md-4 col-xs-6 border-primary d-inline-flex ">
                <div class="card flex-grow-0" style="max-height: 540px">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title text-center">
                                        @items.Name
                                    </h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <img src="@photoPath" asp-append-version="true" class="imageThumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@items.Description</p>
                                <p class="card-text">@items.Price.ToString("c")</p>

                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text">
                                    <a asp-action="Details" asp-controller="Production" asp-route-id="@items.Id" class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill">Show Details</i></a>
                                    <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@items.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart(Price: @items.Price.ToString("c"))</i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    <div class="card-footer mb-3 text-center text-white"> <a asp-action="index" asp-controller="Appliances" class="btn float-right">More....</a></div>
</div>

<div class="container">

    <div class="card-header text-center">
        <h3>Clothing</h3>
    </div>
    @foreach (var items in Model)
    {
        var photoPath = "~/Images/";
        if (string.IsNullOrEmpty(items.Photo))
        {
            photoPath += "me.jpg";
        }
        else
        {
            photoPath += items.Photo;
        }


        if (items.ProduceCategory == ProductCategory.Clothing)
        {


            <div class="col-md-4 col-xs-6 border-primary d-inline-flex ">
                <div class="card " style="max-width: 540px">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title text-center">
                                        @items.Name
                                    </h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <img src="@photoPath" asp-append-version="true" class="imageThumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@items.Description</p>
                                <p class="card-text">@items.Price.ToString("c")</p>

                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text">
                                    <a asp-action="Details" asp-controller="Production" asp-route-id="@items.Id" class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill">Show Details</i></a>
                                    <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@items.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart(Price: @items.Price.ToString("c"))</i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }
    }
    <div class="card-footer mb-3 text-center text-white"> <a asp-action="index" asp-controller="Clothing" class="btn">More....</a></div>
</div>

<div class="container">

    <div class="card-header text-center">
        <h3>Kitchen Equipments</h3>
    </div>
    <div class="card-body col-md-6"></div>
    @foreach (var items in Model)
    {

        var photoPath = "~/Images/";
        if (string.IsNullOrEmpty(items.Photo))
        {
            photoPath += "me.jpg";
        }
        else
        {
            photoPath += items.Photo;
        }
        if (items.ProduceCategory == ProductCategory.Kitchen)
        {

            <div class="col-md-4 col-xs-6 border-primary d-inline-flex ">
                <div class="card" style="max-width: 540px">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title text-center">
                                        @items.Name
                                    </h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <img src="@photoPath" asp-append-version="true" class="imageThumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@items.Description</p>
                                <p class="card-text">@items.Price.ToString("c")</p>

                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text">
                                    <a asp-action="Details" asp-controller="Production" asp-route-id="@items.Id" class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill">Show Details</i></a>
                                    <a asp-action="AddItemToShoppingCart" asp-controller="Order" asp-route-id="@items.Id" class="btn btn-outline-success text-black"><i class="bi bi-cart-plus">Add to cart (Price: @items.Price.ToString("c"))</i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    <div class="card-footer mb-3 text-center text-white"> <a asp-action="index" asp-controller="Kitchen" class="btn float-right text-black">More....</a></div>
</div>
@await Html.PartialAsync("_CreateProduct", "Production")